# Generated by Django 3.2.7 on 2021-09-11 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('confirmed', models.BooleanField(blank=True)),
                ('status_service', models.CharField(choices=[('0', 'Aguardando Confirmação de Atendimento'), ('1', 'Confirmado Atendimento'), ('2', 'Aguardando Confirmação de Doação'), ('3', 'Cancelado'), ('4', 'Concluído')], max_length=1)),
                ('return_recipient', models.TextField(max_length=300)),
                ('points_service', models.FloatField()),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('tagged', models.BooleanField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuester', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(blank=True)),
                ('status_donation', models.CharField(choices=[('0', 'Confirmada'), ('1', 'Precisa Revisar'), ('2', 'Cancelada')], max_length=1)),
                ('customerService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_donation.customerservice')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('material_type', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('points', models.FloatField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_donation.donation')),
            ],
        ),
    ]
